package com.tontine.enums;
public enum NotificationType { RAPPEL_COTISATION, PAIEMENT_RECU, TIRAGE_EFFECTUE, TIRAGE_BENEFICIAIRE, RETARD_PAIEMENT, NOUVEAU_MEMBRE, INVITATION, NOUVEAU_CYCLE, DON_CONFIRME, TIRAGE_SIGNALE }
